name: golearn
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pinput: ^1.2.0
  buttons_tabbar: ^1.3.2
  intl: ^0.17.0
  accordion: ^2.2.3
  shared_preferences: ^2.0.15
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3
  flutter_native_splash: ^2.2.0+1
  retrofit: ^3.0.1+1
  mobx: ^2.0.7+4
  provider: ^6.0.3
  equatable: ^2.0.3
  get_it: ^7.2.0
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  flutter_mobx: ^2.0.6+1
  responsive_sizer: ^3.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  retrofit_generator: ^4.0.1
  flutter_gen_runner: ^4.1.6
  mobx_codegen: ^2.0.7
  flutter_lints: ^1.0.0
  freezed: ^2.0.4
  json_serializable: ^6.2.0

dependency_overrides:
  analyzer: ">=4.2.0 <5.0.0"

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:

    - family: Gilroy_Medium
      fonts:
        - asset: font/Gilroy-Medium.otf
    - family: Gilroy_Bold
      fonts:
        - asset: font/Gilroy-Bold.otf
    - family: Gilroy_Regular
      fonts:
        - asset: font/Gilroy-Regular.otf
